name: main

on:
  push:
    branches: [ main ]

jobs:
#  linter:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v2
#        with:
#          version: v1.37
#
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          file: .infra/docker/Dockerfile
#          push: true
#          tags: dmitriivoitovich/heameelega:latest

  deploy:
#    needs: [ linter, build ]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DB_PASSWORD: ${{secrets.PRODUCTION_DB_PASSWORD}}
        with:
          host: heameele.ga
          username: root
          key: ${{ secrets.SSH_KEY }}
          envs: DOCKERHUB_USERNAME,DOCKERHUB_TOKEN,DB_PASSWORD
          script: |
            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_TOKEN
            export IMAGE=$DOCKERHUB_USERNAME/heameelega:latest
            docker pull IMAGE
            docker stop heameelega || true
            docker run --name heameelega --rm -d -e VIPER_DB_PASSWORD=$DB_PASSWORD -e VIPER_APP_HOST="http://heameele.ga" --network=host $IMAGE
            docker logs heameelega
